### ISSUE TITLE
Integrate different archetypes with different max duration hours for one storage technology

### ISSUE THREAD

**Issue by daniel-rdt** [open-energy-transition/form-energy-storage#13]
For integration of input data from FE, different archetypes for the same storage technology have to be integrated containing different max duration hours. For example, this could be implemented as some loop based on a list input in config.yaml:
```
electricity:
  max_hours:
    battery: [3,4,6]
    H2: 168
```
