### ISSUE TITLE
Fix plotting scripts and make automation more robust

### ISSUE THREAD

**Issue by daniel-rdt** [open-energy-transition/form-energy-storage#34]
There are some issue with the current plotting that needs adjustment. This includes:
- [x] Fixing the plotting of H2 Store capacity (GW). It should plot `H2 Electrolyis` and `H2 Fuel Cell` instead of H2 Store
- [x] Add `H2 Electrolyis` and `H2 Fuel Cell` to Storage dispatch time series plot
- [x] Ammend curtailment and dispatch time series and capacity plotting to be variable to input values (automated)
- [x] Fix capacity plotting for [GWe]
- [x] Add some more KPI information on the plots? (like e.g. total curtailment or CO2 emissions)

**Comment by virio-andreyana** [comment]
![plotting_kpi](https://github.com/user-attachments/assets/f2cdf643-ccbc-4790-bdd2-17d08c648665)

I had spent yesterday on making a modular scheme where you can extract these types of information from a pypsa network, Filters it plot it into two different options: detail (with the values on the side) or overview (with all countries included). To create a plot, you need to specify it in the config with these examples: 

```
kpi:
  country_electricity_system_cost:
    extract: system cost
    exclude: ["EU"]
    carrier_filter: electricity
    group_carrier: pretty
    plot: overview
    plot_kw:
      title: Country electricity system cost
      ylim: [0,100]
      ylabel: Billion EUR/a
```

In the Snakefile, we can use an `expand()` function so that you can create an arbitrary amount of plots depending on what you want to specify with for example `country_electricity_system_cost` as its filename. I'll show you a functioning draft version later in the pull request for kpi_plotting
